name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Select tests to run
        required: true
        default: all
        type: choice
        options:
         - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Copy source code
        uses: actions/checkout@v4
      
      - name: Set up Python env
        uses: actions/setup-python@v5
        with: 
          python-version: "3.9"
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
      
      - name: Install ChromeDriver
        run: |
          # Проверяем версию Chrome
          CHROME_VERSION=$(google-chrome-stable --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
          
          # Устанавливаем необходимые пакеты
          sudo apt install -y wget unzip
          
          # Загружаем нужную версию ChromeDriver
          wget -q "https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)/chromedriver_linux64.zip"
          
          # Разархивируем и перемещаем в правильное место
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          rm chromedriver_linux64.zip
      
      - name: Run Tests
        run: pytest
